services:
    postgres:
        image: postgres:16
        container_name: dataverse-postgres
        restart: always
        environment:
            POSTGRES_DB: dataverse_db
            POSTGRES_USER: ilias_dev
            POSTGRES_PASSWORD: swordFish123!
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
